# Generated by Django 3.2.6 on 2021-08-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_auto_20210809_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameplay_duration',
            field=models.IntegerField(),
        ),
    ]
