# Generated by Django 3.2.6 on 2021-08-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0003_alter_game_gameplay_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
